export const EMPLOYEES_REQUESTED = 'EMPLOYEES_REQUESTED';
export const EMPLOYEES_LOADED = 'EMPLOYEES_LOADED';

export const EMPLOYEE_REQUESTED = 'EMPLOYEE_REQUESTED';
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED';

export const ADD_EMPLOYEE_REQUESTED = 'ADD_EMPLOYEE_REQUESTED';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';

export const EDIT_EMPLOYEE_REQUESTED = 'EDIT_EMPLOYEE_REQUESTED';
export const EMPLOYEE_EDITED = 'EMPLOYEE_EDITED';

export const DELETE_EMPLOYEE_REQUESTED = 'DELETE_EMPLOYEE_REQUESTED';
export const EMPLOYEE_DELETED = 'EMPLOYEE_DELETED';

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';