export const EMPLOYEES_REQUESTED = 'EMPLOYEES_REQUESTED';
export const EMPLOYEES_LOADED = 'EMPLOYEES_LOADED';

export const EMPLOYEE_REQUESTED = 'EMPLOYEE_REQUESTED';
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED';